//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Backyard_PortableEntities : DbContext
    {
        public Backyard_PortableEntities()
            : base("name=Backyard_PortableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAttchmnt> tblAttchmnts { get; set; }
        public virtual DbSet<tblBldg> tblBldgs { get; set; }
        public virtual DbSet<tblBldgOptn> tblBldgOptns { get; set; }
        public virtual DbSet<tblBldgStts_admn> tblBldgStts_admn { get; set; }
        public virtual DbSet<tblClr> tblClrs { get; set; }
        public virtual DbSet<tblCstmr> tblCstmrs { get; set; }
        public virtual DbSet<tblDlr> tblDlrs { get; set; }
        public virtual DbSet<tblDlrLgn> tblDlrLgns { get; set; }
        public virtual DbSet<tblDrvr> tblDrvrs { get; set; }
        public virtual DbSet<tblFnncCmpny> tblFnncCmpnies { get; set; }
        public virtual DbSet<tblFnncTyp_admn> tblFnncTyp_admn { get; set; }
        public virtual DbSet<tblMnfctrr_admn> tblMnfctrr_admn { get; set; }
        public virtual DbSet<tblOptn> tblOptns { get; set; }
        public virtual DbSet<tblOrdr> tblOrdrs { get; set; }
        public virtual DbSet<tblOrdrStts_admn> tblOrdrStts_admn { get; set; }
        public virtual DbSet<tblPmnt> tblPmnts { get; set; }
        public virtual DbSet<tblPmntMthd_admn> tblPmntMthd_admn { get; set; }
        public virtual DbSet<tblStyl> tblStyls { get; set; }
        public virtual DbSet<tblStylSz> tblStylSzs { get; set; }
        public virtual DbSet<tblStylTyp_admn> tblStylTyp_admn { get; set; }
        public virtual DbSet<tblSz> tblSzs { get; set; }
        public virtual DbSet<tblTxCd> tblTxCds { get; set; }
        public virtual DbSet<tblUsrLgn> tblUsrLgns { get; set; }
    }
}
