//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttchmnt
    {
        public int ordrIDfk { get; set; }
        public int AttchmntID { get; set; }
        public string AttchmntNm { get; set; }
        public byte[] Attchmnt { get; set; }
    
        public virtual tblOrdr tblOrdr { get; set; }
    }
}
