//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBldg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBldg()
        {
            this.tblBldgOptns = new HashSet<tblBldgOptn>();
            this.tblOrdrs = new HashSet<tblOrdr>();
        }
    
        public int BldgID { get; set; }
        public Nullable<int> UnqNmbr { get; set; }
        public string SrlNmbr { get; set; }
        public Nullable<decimal> BsPrc { get; set; }
        public Nullable<bool> isAvlbl { get; set; }
        public Nullable<int> StlyIDfk { get; set; }
        public Nullable<int> SzIDfk { get; set; }
        public Nullable<int> MnfctrrIDfk { get; set; }
        public Nullable<int> DlrIDfk { get; set; }
        public Nullable<int> BldgSttsIDfk { get; set; }
        public Nullable<int> RfClrIDfk { get; set; }
        public Nullable<int> SdClrIDfk { get; set; }
        public Nullable<int> TrmClrIDfk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBldgOptn> tblBldgOptns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrdr> tblOrdrs { get; set; }
        public virtual tblClr tblClr { get; set; }
        public virtual tblClr tblClr1 { get; set; }
        public virtual tblClr tblClr2 { get; set; }
        public virtual tblMnfctrr_admn tblMnfctrr_admn { get; set; }
        public virtual tblBldgStts_admn tblBldgStts_admn { get; set; }
    }
}
