//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBldgOptn
    {
        public int BldgIDfk { get; set; }
        public int BldgOptnID { get; set; }
        public Nullable<int> OptnIDfk { get; set; }
        public Nullable<decimal> OptnPrc { get; set; }
    
        public virtual tblBldg tblBldg { get; set; }
        public virtual tblOptn tblOptn { get; set; }
    }
}
