//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCstmr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCstmr()
        {
            this.tblOrdrs = new HashSet<tblOrdr>();
        }
    
        public int CstmrID { get; set; }
        public string Cstmr { get; set; }
        public string CstmrPhn { get; set; }
        public string CstmrEml { get; set; }
        public string CstrmStrt { get; set; }
        public string CstmrCty { get; set; }
        public string CstmrSt { get; set; }
        public string CstmrZp { get; set; }
        public Nullable<int> TxCdIDfk { get; set; }
        public string CstmrNts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrdr> tblOrdrs { get; set; }
        public virtual tblTxCd tblTxCd { get; set; }
    }
}
