//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClr()
        {
            this.tblBldgs = new HashSet<tblBldg>();
            this.tblBldgs1 = new HashSet<tblBldg>();
            this.tblBldgs2 = new HashSet<tblBldg>();
        }
    
        public int ClrID { get; set; }
        public string Dscrptn { get; set; }
        public string HxVlu { get; set; }
        public string ClrCd { get; set; }
        public Nullable<decimal> R { get; set; }
        public Nullable<decimal> G { get; set; }
        public Nullable<decimal> B { get; set; }
        public string ClrFm { get; set; }
        public string ClrUs { get; set; }
        public Nullable<bool> WtFrClr { get; set; }
        public Nullable<bool> ActvClr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBldg> tblBldgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBldg> tblBldgs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBldg> tblBldgs2 { get; set; }
    }
}
