//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrvr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDrvr()
        {
            this.tblOrdrs = new HashSet<tblOrdr>();
        }
    
        public int DrvrID { get; set; }
        public string Drvr { get; set; }
        public string DrvrPhn { get; set; }
        public string DrvrEml { get; set; }
        public string DrvrStrt { get; set; }
        public string DrvrCty { get; set; }
        public string DrvrSt { get; set; }
        public string DrvrZp { get; set; }
        public Nullable<int> TxCdIDfk { get; set; }
        public string DrvrNts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrdr> tblOrdrs { get; set; }
        public virtual tblTxCd tblTxCd { get; set; }
    }
}
