//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDlr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDlr()
        {
            this.tblDlrLgns = new HashSet<tblDlrLgn>();
            this.tblOrdrs = new HashSet<tblOrdr>();
        }
    
        public int DlrID { get; set; }
        public Nullable<bool> DlrActv { get; set; }
        public string Dlr { get; set; }
        public Nullable<decimal> CmmssnRt { get; set; }
        public string DlrStrt { get; set; }
        public string DlrCty { get; set; }
        public string DlrSt { get; set; }
        public string DlrZp { get; set; }
        public Nullable<int> TxCdIDfk { get; set; }
        public string DlrNts { get; set; }
        public string PrmryCntct { get; set; }
        public string CntctPhn { get; set; }
        public string CntctEml { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDlrLgn> tblDlrLgns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrdr> tblOrdrs { get; set; }
        public virtual tblTxCd tblTxCd { get; set; }
    }
}
