//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDlrLgn
    {
        public int DlrIDfk { get; set; }
        public int DlrLgnID { get; set; }
        public string DlrLgn { get; set; }
        public string DlrPwrd { get; set; }
        public Nullable<decimal> DlrAccssLvl { get; set; }
    
        public virtual tblDlr tblDlr { get; set; }
    }
}
