//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrdr()
        {
            this.tblAttchmnts = new HashSet<tblAttchmnt>();
            this.tblPmnts = new HashSet<tblPmnt>();
        }
    
        public int OrdrID { get; set; }
        public Nullable<int> BldgIDfk { get; set; }
        public Nullable<int> DlrIDfk { get; set; }
        public Nullable<int> CstmrIDfk { get; set; }
        public Nullable<int> DrvrIDfk { get; set; }
        public Nullable<int> FnncTypIDfk { get; set; }
        public Nullable<int> OrdrSttsIDfk { get; set; }
        public Nullable<int> FnncCmpnyIDfk { get; set; }
        public Nullable<int> TxCdIDfk { get; set; }
        public string DlvryStrt { get; set; }
        public string DlvryCty { get; set; }
        public string DlvrySt { get; set; }
        public string DlvryZp { get; set; }
        public Nullable<bool> Apprvd { get; set; }
        public Nullable<bool> Lckd { get; set; }
        public Nullable<bool> BldgLckd { get; set; }
        public Nullable<bool> DlvryAddrssSm { get; set; }
        public Nullable<bool> Pd { get; set; }
        public Nullable<bool> Dlvrd { get; set; }
        public Nullable<System.DateTime> DtOrdr { get; set; }
        public Nullable<System.DateTime> DtPd { get; set; }
        public Nullable<System.DateTime> DtDlvrPlnnd { get; set; }
        public Nullable<System.DateTime> DtDlvrd { get; set; }
        public Nullable<System.DateTime> DtCnclld { get; set; }
        public Nullable<decimal> PrcOnst { get; set; }
        public Nullable<decimal> PrcDlvry { get; set; }
        public Nullable<decimal> ScrtyDpst { get; set; }
        public Nullable<decimal> CstRdctn { get; set; }
        public Nullable<decimal> CstRdctnNt { get; set; }
        public Nullable<decimal> AmtRTO { get; set; }
        public Nullable<decimal> DsctRt { get; set; }
        public Nullable<decimal> DsctAmnt { get; set; }
        public Nullable<decimal> PrcAdjstmnt { get; set; }
        public Nullable<decimal> AmtTxbl { get; set; }
        public Nullable<decimal> AmtTtl { get; set; }
        public Nullable<decimal> AmtPd { get; set; }
        public Nullable<decimal> PrcWTx { get; set; }
        public Nullable<decimal> Pmt { get; set; }
        public Nullable<decimal> AmtBll { get; set; }
        public Nullable<int> RntTrms { get; set; }
        public string Nts { get; set; }
        public string DlvryNts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttchmnt> tblAttchmnts { get; set; }
        public virtual tblBldg tblBldg { get; set; }
        public virtual tblCstmr tblCstmr { get; set; }
        public virtual tblDlr tblDlr { get; set; }
        public virtual tblDrvr tblDrvr { get; set; }
        public virtual tblFnncCmpny tblFnncCmpny { get; set; }
        public virtual tblFnncTyp_admn tblFnncTyp_admn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPmnt> tblPmnts { get; set; }
        public virtual tblOrdrStts_admn tblOrdrStts_admn { get; set; }
        public virtual tblTxCd tblTxCd { get; set; }
    }
}
