//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPmntMthd_admn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPmntMthd_admn()
        {
            this.tblPmnts = new HashSet<tblPmnt>();
        }
    
        public int PmntMthdID { get; set; }
        public string PmntMthdCd { get; set; }
        public string PmntMthdDsc { get; set; }
        public Nullable<int> PmntMthdClss { get; set; }
        public Nullable<int> MthdOrdrBy { get; set; }
        public Nullable<decimal> MthdFees { get; set; }
        public string MthdNts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPmnt> tblPmnts { get; set; }
    }
}
