//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPmnt
    {
        public int OrdrIDfk { get; set; }
        public int PmntID { get; set; }
        public Nullable<int> PmntMthIDfk { get; set; }
        public Nullable<System.DateTime> DtPd { get; set; }
        public Nullable<System.DateTime> DtRcvd { get; set; }
        public Nullable<decimal> PmntTtl { get; set; }
        public Nullable<decimal> PmntDtl { get; set; }
        public Nullable<decimal> PmntTx { get; set; }
        public Nullable<decimal> PmntFee { get; set; }
        public string Nmbr { get; set; }
        public string PmntNts { get; set; }
    
        public virtual tblOrdr tblOrdr { get; set; }
        public virtual tblPmntMthd_admn tblPmntMthd_admn { get; set; }
    }
}
