//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackyardPortableCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStylSz
    {
        public int StylIDfk { get; set; }
        public int SzIDfk { get; set; }
        public int StylSzID { get; set; }
        public Nullable<decimal> BsPrc { get; set; }
        public string Nts { get; set; }
        public Nullable<bool> Actv { get; set; }
    
        public virtual tblStyl tblStyl { get; set; }
        public virtual tblSz tblSz { get; set; }
    }
}
